[modules]
autoload = yes

; Ensure key modules are loaded
load = res_ari.so
load = res_ari_channels.so
load = res_ari_bridges.so
load = res_ari_playbacks.so
load = res_http_websocket.so
load = res_stasis.so
load = app_audiosocket.so
load = res_pjsip.so
load = res_pjsip_session.so
load = res_pjsip_outbound_registration.so

; Disable unused modules
noload = chan_sip.so
noload = app_voicemail.so
noload = res_adsi.so
